# Introduccion a NumPy

### Lo primero que veremos es como importar la Libreria de Numpy a continuacion un ejemplo

In [2]:
import numpy as np

### Para obtener la version de nuestro Numpy que ha sido importado

In [3]:
np.__version__

'2.0.0'

### Para ver la Informacion de la Configuracion de nuestra Libreria Numpy usamos el metodo show_config()

In [4]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-zh8sc4vi/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-zh8sc4vi/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-zh8sc4vi/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-zh8sc4vi/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64B

### Obteniendo informacion de la Funcion add

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

## Ahora vamos a realizar algunos Ejercicios
1. Comprobar si Alguno de los elementos de una lista es 0 
2. Comprobar si en una Lista existe almenos un numero distinto de 0
3. Comprobar si cada uno de los elementos de un arreglo son finitos o no nulos
4. Comprobar si los elementos de un arreglo infinitos (positivo o negativo)

### 1. Comprobar si Alguno de los elementos de una lista es 0 

### En NumPy tenemos un metodo llamado all() que al pasarle una lista como parametro te retorna false si dentro de la lista hay un 0 y true si no hay un 0

In [6]:
# Vamos a declarar un lista
list_numbers = [3,3,8,2,8,4,9,0,0,8,6,4,2,1,2,5,6,7,8,9,123,567345,39]

# Aqui usamos el metodo all()
np.all(list_numbers)# Aqui nos retorna false porque hay dos 0's en el array

np.False_

In [9]:
numbers = [1,2,3,4,5,6,7,8,9]
np.all(numbers)# Aqui no retorna true porque efectivamente no se tiene un 0 en el array

np.True_

### 2. Comprobar si en una Lista existe almenos un numero distinto de 0

In [10]:
#Creando una lista con NumPy
zeros = np.array([0,9,0,0])
print(zeros)

[0 9 0 0]


### En NumPy tambien hay un metodo llamado any() , para ver si un array contiene un valor que es distinto de 0 si es distinto de 0 retorna un true si no retorna un false

In [11]:
np.any(zeros)# aqui retorna true porque si hay un elementos en el array que es distinto de 0

np.True_

In [12]:
not_zeros = np.array([0,0,0,0,0])
print(not_zeros)
np.any(not_zeros) # aqui nos retorna false porque no hay ningun numero diferente de 0

[0 0 0 0 0]


np.False_

### 3. Comprobar si cada uno de los elementos de un arreglo son finitos o no nulos

#### np.nan es para crear un valor None o nulos y np.inf es para denotar los valores infinitos

In [14]:
print(np.nan) # para crear un valor NAN not a number
print(np.inf) # para crear un valor infinito 

nan
inf


In [18]:
infinite_list = [1,2,3,4,np.nan,np.inf,-np.inf, np.inf]
print(infinite_list)

[1, 2, 3, 4, nan, inf, -inf, inf]


### En NumPy tenemos el metodo isfinite() que comprueba si en el array hay elementos nulos o infinitos cuando son nulos a infinitos retorna un false , cuando son finitos retorna un true

In [19]:
np.isfinite(infinite_list)

array([ True,  True,  True,  True, False, False, False, False])

### 4. Comprobar si los elementos de un arreglo son infinitos (positivo o negativo)

In [22]:
infinite_list = np.array([0,1,2, np.inf, -np.inf])
print(infinite_list)

[  0.   1.   2.  inf -inf]


### El metodo isinf() te retorna true si el elemento es del tipo np.inf y false si el elemento es otro tipo de elemento

In [23]:
np.isinf(infinite_list)

array([False, False, False,  True,  True])

### El creacion de una matriz n-dimencional con Numpy

In [36]:
array_n_2d = np.array([[1., 0., 0.],
 [0., 1., 2.]])
print(array_n_d)

[[1. 0. 0.]
 [0. 1. 2.]]


### Para saber el numero de ejes o dimensiones de un matriz

In [37]:
array_n_2d.ndim

2

In [45]:
array_n_2d.shape

(2, 3)

### Creacion de una matriz de 3 ejes o 3 dimensiones

In [41]:
array_n_3d = np.array([[[1, 0, 2], [4, 7, 2], [1, 1, 0]],[[3, 4, -2], [4, 0, 2], [9, 1, 0]]])
print(array_n_3d)

[[[ 1  0  2]
  [ 4  7  2]
  [ 1  1  0]]

 [[ 3  4 -2]
  [ 4  0  2]
  [ 9  1  0]]]


In [42]:
array_n_3d.ndim

3

### Funcion de numpy para saber

In [44]:
array_n_3d.shape

(2, 3, 3)